### ISSUE TITLE
Possible to use for greyscale style image?

### ISSUE THREAD

**Issue by JoeyJoeJoeJunior** [ashwindcruz/style-transfer#2]
The notebook is really helping to understand style transfer. But I was wondering if it is possible to extract the style from greyscale images?
If I try to extract the style I always get a blur of grey.

**Comment by JoeyJoeJoeJunior** [comment]
Used the wrong format. My mistake

**Comment by ashwindcruz** [comment]
Glad to hear you got it working :)
